export const LOADING_HIDE = 'COMMONSTATUS/LOADING_HIDE';
export const LOADING_SHOW = 'COMMONSTATUS/LOADING_SHOW';
export const MSG_HIDE = 'COMMONSTATUS/MSG_HIDE';
export const MSG_SHOW = 'COMMONSTATUS/MSG_SHOW';
